### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by yoon308** [yoon308/fizzbuzz-for-me#1]
## 목표

나 혼자 완성해보는 fizzbuzz

## 요구사항
- 범위 : 1~20까지의 정수

## Tasks

- [x] print 'fizz' if i is times of 3.
- [x]  print i itself for ant other cases.
- [ ] print 'buzz' if i is times of 5.
- [ ] print 'fizzbuzz' if i is times of 15.

## References

- https://en.wikipedia.org/wiki/Fizz_buzz
